substitutions:
  devicename: utility_bridge
  upper_devicename: Utility Bridge

esphome:
  name: utility-bridge
  comment: Fan controller

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 8MB
  framework:
    type: esp-idf
    #platform_version: "6.8.1"
    platform_version: https://github.com/stintel/platform-espressif32#develop
    #platform_version: https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF52
    version: "5.2.2"
    #version: 5.1.2
    # source: https://github.com/tasmota/esp-idf/releases/download/v5.1.2.240221/esp-idf-v5.1.2.zip
#    type: arduino
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_utility_bridge_api_key

  services:
    - service: set_speed
      variables:
        run_speed: int
        run_time: int
      then:
        - lambda: |-
            zehnder_fan->setSpeed(run_speed, run_time);

ota:
  password: !secret esphome_utility_bridge_ota_password
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: !secret wifi_ip_utility_bridge
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_gateway

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "utility-bridge Fallback"
    password: !secret esphome_utility_bridge_ap_password

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Amsterdam

switch:
  - platform: restart
    id: ${devicename}_esphome_restart
    name: ${upper_devicename} restart

button:

  - platform: template
    id: ${devicename}_high_10
    name: ${upper_devicename} High for 10m
    on_press:
      then:
        lambda: |-
          zehnder_fan->setSpeed(3, 10);

  - platform: template
    id: ${devicename}_high_30
    name: ${upper_devicename} High for 30m
    on_press:
      then:
        lambda: |-
          zehnder_fan->setSpeed(3, 30);

  - platform: factory_reset
    id: ${devicename}_esphome_reset
    name: Restart with factory default settings

# Load external components
# https://esphome.io/components/external_components.html#external-components-git
external_components:
  - source: components/
  # - source: github://rosmo/ESPHome-Zehnder-RF

# SPI
spi:
  clk_pin: GPIO13   # SCK
  mosi_pin: GPIO12  # MOSI
  miso_pin: GPIO11  # MISO

# nRF905 config
nrf905:
  id: "nrf905_rf"
  cs_pin: GPIO23    # CSN, NSS
  cd_pin: GPIO22    # CD
  ce_pin: GPIO21
  pwr_pin: GPIO20
  txen_pin: GPIO19  # TXEN
  # We don't need AM and DR at the moment as they are read from the inernal registers
  # am_pin: GPIO32
  # dr_pin: GPIO35

# The FAN controller
fan:
  - platform: zehnder
    id: zehnder_fan
    name: "Ventilation"
    nrf905: nrf905_rf
    update_interval: "60s"
